// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/t4doc/v1/document.proto

package t4docpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Change_Type int32

const (
	Change_TYPE_UNSPECIFIED Change_Type = 0
	Change_PUT              Change_Type = 1
	Change_DELETE           Change_Type = 2
)

// Enum value maps for Change_Type.
var (
	Change_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "PUT",
		2: "DELETE",
	}
	Change_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"PUT":              1,
		"DELETE":           2,
	}
)

func (x Change_Type) Enum() *Change_Type {
	p := new(Change_Type)
	*p = x
	return p
}

func (x Change_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Change_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_t4doc_v1_document_proto_enumTypes[0].Descriptor()
}

func (Change_Type) Type() protoreflect.EnumType {
	return &file_proto_t4doc_v1_document_proto_enumTypes[0]
}

func (x Change_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Change_Type.Descriptor instead.
func (Change_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{10, 0}
}

type IndexSpec_FieldType int32

const (
	IndexSpec_FIELD_TYPE_UNSPECIFIED IndexSpec_FieldType = 0
	IndexSpec_STRING                 IndexSpec_FieldType = 1
	IndexSpec_INT64                  IndexSpec_FieldType = 2
	IndexSpec_BOOL                   IndexSpec_FieldType = 3
)

// Enum value maps for IndexSpec_FieldType.
var (
	IndexSpec_FieldType_name = map[int32]string{
		0: "FIELD_TYPE_UNSPECIFIED",
		1: "STRING",
		2: "INT64",
		3: "BOOL",
	}
	IndexSpec_FieldType_value = map[string]int32{
		"FIELD_TYPE_UNSPECIFIED": 0,
		"STRING":                 1,
		"INT64":                  2,
		"BOOL":                   3,
	}
)

func (x IndexSpec_FieldType) Enum() *IndexSpec_FieldType {
	p := new(IndexSpec_FieldType)
	*p = x
	return p
}

func (x IndexSpec_FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexSpec_FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_t4doc_v1_document_proto_enumTypes[1].Descriptor()
}

func (IndexSpec_FieldType) Type() protoreflect.EnumType {
	return &file_proto_t4doc_v1_document_proto_enumTypes[1]
}

func (x IndexSpec_FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexSpec_FieldType.Descriptor instead.
func (IndexSpec_FieldType) EnumDescriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{13, 0}
}

type Document struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Collection     string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Json           []byte                 `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
	Revision       int64                  `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	CreateRevision int64                  `protobuf:"varint,5,opt,name=create_revision,json=createRevision,proto3" json:"create_revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

func (x *Document) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Document) GetCreateRevision() int64 {
	if x != nil {
		return x.CreateRevision
	}
	return 0
}

type WriteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Json          []byte                 `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteDocumentRequest) Reset() {
	*x = WriteDocumentRequest{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteDocumentRequest) ProtoMessage() {}

func (x *WriteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteDocumentRequest.ProtoReflect.Descriptor instead.
func (*WriteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{1}
}

func (x *WriteDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *WriteDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WriteDocumentRequest) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type WriteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteDocumentResponse) Reset() {
	*x = WriteDocumentResponse{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteDocumentResponse) ProtoMessage() {}

func (x *WriteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteDocumentResponse.ProtoReflect.Descriptor instead.
func (*WriteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{2}
}

func (x *WriteDocumentResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{3}
}

func (x *GetDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{4}
}

func (x *GetDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PatchDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	MergePatch    []byte                 `protobuf:"bytes,3,opt,name=merge_patch,json=mergePatch,proto3" json:"merge_patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchDocumentRequest) Reset() {
	*x = PatchDocumentRequest{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchDocumentRequest) ProtoMessage() {}

func (x *PatchDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchDocumentRequest.ProtoReflect.Descriptor instead.
func (*PatchDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{6}
}

func (x *PatchDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *PatchDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PatchDocumentRequest) GetMergePatch() []byte {
	if x != nil {
		return x.MergePatch
	}
	return nil
}

type FindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Filter        *Filter                `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	AllowScan     bool                   `protobuf:"varint,4,opt,name=allow_scan,json=allowScan,proto3" json:"allow_scan,omitempty"`
	MaxScan       int64                  `protobuf:"varint,5,opt,name=max_scan,json=maxScan,proto3" json:"max_scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{7}
}

func (x *FindRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *FindRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *FindRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindRequest) GetAllowScan() bool {
	if x != nil {
		return x.AllowScan
	}
	return false
}

func (x *FindRequest) GetMaxScan() int64 {
	if x != nil {
		return x.MaxScan
	}
	return 0
}

type FindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindResponse) Reset() {
	*x = FindResponse{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse) ProtoMessage() {}

func (x *FindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse.ProtoReflect.Descriptor instead.
func (*FindResponse) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{8}
}

func (x *FindResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Filter        *Filter                `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{9}
}

func (x *WatchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *WatchRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Change_Type            `protobuf:"varint,1,opt,name=type,proto3,enum=t4doc.v1.Change_Type" json:"type,omitempty"`
	Document      *Document              `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	Revision      int64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{10}
}

func (x *Change) GetType() Change_Type {
	if x != nil {
		return x.Type
	}
	return Change_TYPE_UNSPECIFIED
}

func (x *Change) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *Change) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type CreateIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Index         *IndexSpec             `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndexRequest) Reset() {
	*x = CreateIndexRequest{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexRequest) ProtoMessage() {}

func (x *CreateIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexRequest.ProtoReflect.Descriptor instead.
func (*CreateIndexRequest) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{11}
}

func (x *CreateIndexRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *CreateIndexRequest) GetIndex() *IndexSpec {
	if x != nil {
		return x.Index
	}
	return nil
}

type CreateIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndexResponse) Reset() {
	*x = CreateIndexResponse{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexResponse) ProtoMessage() {}

func (x *CreateIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexResponse.ProtoReflect.Descriptor instead.
func (*CreateIndexResponse) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{12}
}

type IndexSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Type          IndexSpec_FieldType    `protobuf:"varint,3,opt,name=type,proto3,enum=t4doc.v1.IndexSpec_FieldType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexSpec) Reset() {
	*x = IndexSpec{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexSpec) ProtoMessage() {}

func (x *IndexSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexSpec.ProtoReflect.Descriptor instead.
func (*IndexSpec) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{13}
}

func (x *IndexSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IndexSpec) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *IndexSpec) GetType() IndexSpec_FieldType {
	if x != nil {
		return x.Type
	}
	return IndexSpec_FIELD_TYPE_UNSPECIFIED
}

type Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Filter_Eq
	//	*Filter_And
	Kind          isFilter_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{14}
}

func (x *Filter) GetKind() isFilter_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Filter) GetEq() *EqFilter {
	if x != nil {
		if x, ok := x.Kind.(*Filter_Eq); ok {
			return x.Eq
		}
	}
	return nil
}

func (x *Filter) GetAnd() *AndFilter {
	if x != nil {
		if x, ok := x.Kind.(*Filter_And); ok {
			return x.And
		}
	}
	return nil
}

type isFilter_Kind interface {
	isFilter_Kind()
}

type Filter_Eq struct {
	Eq *EqFilter `protobuf:"bytes,1,opt,name=eq,proto3,oneof"`
}

type Filter_And struct {
	And *AndFilter `protobuf:"bytes,2,opt,name=and,proto3,oneof"`
}

func (*Filter_Eq) isFilter_Kind() {}

func (*Filter_And) isFilter_Kind() {}

type EqFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value         *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EqFilter) Reset() {
	*x = EqFilter{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EqFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EqFilter) ProtoMessage() {}

func (x *EqFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EqFilter.ProtoReflect.Descriptor instead.
func (*EqFilter) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{15}
}

func (x *EqFilter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *EqFilter) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type AndFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*Filter              `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AndFilter) Reset() {
	*x = AndFilter{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AndFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndFilter) ProtoMessage() {}

func (x *AndFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndFilter.ProtoReflect.Descriptor instead.
func (*AndFilter) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{16}
}

func (x *AndFilter) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_StringValue
	//	*Value_Int64Value
	//	*Value_BoolValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_t4doc_v1_document_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_t4doc_v1_document_proto_rawDescGZIP(), []int{17}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_Int64Value struct {
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_Int64Value) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

var File_proto_t4doc_v1_document_proto protoreflect.FileDescriptor

const file_proto_t4doc_v1_document_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/t4doc/v1/document.proto\x12\bt4doc.v1\"\x93\x01\n" +
	"\bDocument\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04json\x18\x03 \x01(\fR\x04json\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x03R\brevision\x12'\n" +
	"\x0fcreate_revision\x18\x05 \x01(\x03R\x0ecreateRevision\"Z\n" +
	"\x14WriteDocumentRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04json\x18\x03 \x01(\fR\x04json\"3\n" +
	"\x15WriteDocumentResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\"D\n" +
	"\x12GetDocumentRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"E\n" +
	"\x13GetDocumentResponse\x12.\n" +
	"\bdocument\x18\x01 \x01(\v2\x12.t4doc.v1.DocumentR\bdocument\"G\n" +
	"\x15DeleteDocumentRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"g\n" +
	"\x14PatchDocumentRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerge_patch\x18\x03 \x01(\fR\n" +
	"mergePatch\"\xa7\x01\n" +
	"\vFindRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12(\n" +
	"\x06filter\x18\x02 \x01(\v2\x10.t4doc.v1.FilterR\x06filter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x1d\n" +
	"\n" +
	"allow_scan\x18\x04 \x01(\bR\tallowScan\x12\x19\n" +
	"\bmax_scan\x18\x05 \x01(\x03R\amaxScan\"@\n" +
	"\fFindResponse\x120\n" +
	"\tdocuments\x18\x01 \x03(\v2\x12.t4doc.v1.DocumentR\tdocuments\"X\n" +
	"\fWatchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12(\n" +
	"\x06filter\x18\x02 \x01(\v2\x10.t4doc.v1.FilterR\x06filter\"\xb2\x01\n" +
	"\x06Change\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.t4doc.v1.Change.TypeR\x04type\x12.\n" +
	"\bdocument\x18\x02 \x01(\v2\x12.t4doc.v1.DocumentR\bdocument\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\"1\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03PUT\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\"_\n" +
	"\x12CreateIndexRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12)\n" +
	"\x05index\x18\x02 \x01(\v2\x13.t4doc.v1.IndexSpecR\x05index\"\x15\n" +
	"\x13CreateIndexResponse\"\xb2\x01\n" +
	"\tIndexSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.t4doc.v1.IndexSpec.FieldTypeR\x04type\"H\n" +
	"\tFieldType\x12\x1a\n" +
	"\x16FIELD_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STRING\x10\x01\x12\t\n" +
	"\x05INT64\x10\x02\x12\b\n" +
	"\x04BOOL\x10\x03\"_\n" +
	"\x06Filter\x12$\n" +
	"\x02eq\x18\x01 \x01(\v2\x12.t4doc.v1.EqFilterH\x00R\x02eq\x12'\n" +
	"\x03and\x18\x02 \x01(\v2\x13.t4doc.v1.AndFilterH\x00R\x03andB\x06\n" +
	"\x04kind\"G\n" +
	"\bEqFilter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.t4doc.v1.ValueR\x05value\"7\n" +
	"\tAndFilter\x12*\n" +
	"\afilters\x18\x01 \x03(\v2\x10.t4doc.v1.FilterR\afilters\"x\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vint64_value\x18\x02 \x01(\x03H\x00R\n" +
	"int64Value\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValueB\x06\n" +
	"\x04kind2\xef\x04\n" +
	"\rDocumentStore\x12I\n" +
	"\x06Insert\x12\x1e.t4doc.v1.WriteDocumentRequest\x1a\x1f.t4doc.v1.WriteDocumentResponse\x12F\n" +
	"\x03Put\x12\x1e.t4doc.v1.WriteDocumentRequest\x1a\x1f.t4doc.v1.WriteDocumentResponse\x12B\n" +
	"\x03Get\x12\x1c.t4doc.v1.GetDocumentRequest\x1a\x1d.t4doc.v1.GetDocumentResponse\x12J\n" +
	"\x06Delete\x12\x1f.t4doc.v1.DeleteDocumentRequest\x1a\x1f.t4doc.v1.WriteDocumentResponse\x12H\n" +
	"\x05Patch\x12\x1e.t4doc.v1.PatchDocumentRequest\x1a\x1f.t4doc.v1.WriteDocumentResponse\x125\n" +
	"\x04Find\x12\x15.t4doc.v1.FindRequest\x1a\x16.t4doc.v1.FindResponse\x129\n" +
	"\n" +
	"FindStream\x12\x15.t4doc.v1.FindRequest\x1a\x12.t4doc.v1.Document0\x01\x123\n" +
	"\x05Watch\x12\x16.t4doc.v1.WatchRequest\x1a\x10.t4doc.v1.Change0\x01\x12J\n" +
	"\vCreateIndex\x12\x1c.t4doc.v1.CreateIndexRequest\x1a\x1d.t4doc.v1.CreateIndexResponseB*Z(github.com/t4db/t4/t4doc/t4docpb;t4docpbb\x06proto3"

var (
	file_proto_t4doc_v1_document_proto_rawDescOnce sync.Once
	file_proto_t4doc_v1_document_proto_rawDescData []byte
)

func file_proto_t4doc_v1_document_proto_rawDescGZIP() []byte {
	file_proto_t4doc_v1_document_proto_rawDescOnce.Do(func() {
		file_proto_t4doc_v1_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_t4doc_v1_document_proto_rawDesc), len(file_proto_t4doc_v1_document_proto_rawDesc)))
	})
	return file_proto_t4doc_v1_document_proto_rawDescData
}

var file_proto_t4doc_v1_document_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_t4doc_v1_document_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_t4doc_v1_document_proto_goTypes = []any{
	(Change_Type)(0),              // 0: t4doc.v1.Change.Type
	(IndexSpec_FieldType)(0),      // 1: t4doc.v1.IndexSpec.FieldType
	(*Document)(nil),              // 2: t4doc.v1.Document
	(*WriteDocumentRequest)(nil),  // 3: t4doc.v1.WriteDocumentRequest
	(*WriteDocumentResponse)(nil), // 4: t4doc.v1.WriteDocumentResponse
	(*GetDocumentRequest)(nil),    // 5: t4doc.v1.GetDocumentRequest
	(*GetDocumentResponse)(nil),   // 6: t4doc.v1.GetDocumentResponse
	(*DeleteDocumentRequest)(nil), // 7: t4doc.v1.DeleteDocumentRequest
	(*PatchDocumentRequest)(nil),  // 8: t4doc.v1.PatchDocumentRequest
	(*FindRequest)(nil),           // 9: t4doc.v1.FindRequest
	(*FindResponse)(nil),          // 10: t4doc.v1.FindResponse
	(*WatchRequest)(nil),          // 11: t4doc.v1.WatchRequest
	(*Change)(nil),                // 12: t4doc.v1.Change
	(*CreateIndexRequest)(nil),    // 13: t4doc.v1.CreateIndexRequest
	(*CreateIndexResponse)(nil),   // 14: t4doc.v1.CreateIndexResponse
	(*IndexSpec)(nil),             // 15: t4doc.v1.IndexSpec
	(*Filter)(nil),                // 16: t4doc.v1.Filter
	(*EqFilter)(nil),              // 17: t4doc.v1.EqFilter
	(*AndFilter)(nil),             // 18: t4doc.v1.AndFilter
	(*Value)(nil),                 // 19: t4doc.v1.Value
}
var file_proto_t4doc_v1_document_proto_depIdxs = []int32{
	2,  // 0: t4doc.v1.GetDocumentResponse.document:type_name -> t4doc.v1.Document
	16, // 1: t4doc.v1.FindRequest.filter:type_name -> t4doc.v1.Filter
	2,  // 2: t4doc.v1.FindResponse.documents:type_name -> t4doc.v1.Document
	16, // 3: t4doc.v1.WatchRequest.filter:type_name -> t4doc.v1.Filter
	0,  // 4: t4doc.v1.Change.type:type_name -> t4doc.v1.Change.Type
	2,  // 5: t4doc.v1.Change.document:type_name -> t4doc.v1.Document
	15, // 6: t4doc.v1.CreateIndexRequest.index:type_name -> t4doc.v1.IndexSpec
	1,  // 7: t4doc.v1.IndexSpec.type:type_name -> t4doc.v1.IndexSpec.FieldType
	17, // 8: t4doc.v1.Filter.eq:type_name -> t4doc.v1.EqFilter
	18, // 9: t4doc.v1.Filter.and:type_name -> t4doc.v1.AndFilter
	19, // 10: t4doc.v1.EqFilter.value:type_name -> t4doc.v1.Value
	16, // 11: t4doc.v1.AndFilter.filters:type_name -> t4doc.v1.Filter
	3,  // 12: t4doc.v1.DocumentStore.Insert:input_type -> t4doc.v1.WriteDocumentRequest
	3,  // 13: t4doc.v1.DocumentStore.Put:input_type -> t4doc.v1.WriteDocumentRequest
	5,  // 14: t4doc.v1.DocumentStore.Get:input_type -> t4doc.v1.GetDocumentRequest
	7,  // 15: t4doc.v1.DocumentStore.Delete:input_type -> t4doc.v1.DeleteDocumentRequest
	8,  // 16: t4doc.v1.DocumentStore.Patch:input_type -> t4doc.v1.PatchDocumentRequest
	9,  // 17: t4doc.v1.DocumentStore.Find:input_type -> t4doc.v1.FindRequest
	9,  // 18: t4doc.v1.DocumentStore.FindStream:input_type -> t4doc.v1.FindRequest
	11, // 19: t4doc.v1.DocumentStore.Watch:input_type -> t4doc.v1.WatchRequest
	13, // 20: t4doc.v1.DocumentStore.CreateIndex:input_type -> t4doc.v1.CreateIndexRequest
	4,  // 21: t4doc.v1.DocumentStore.Insert:output_type -> t4doc.v1.WriteDocumentResponse
	4,  // 22: t4doc.v1.DocumentStore.Put:output_type -> t4doc.v1.WriteDocumentResponse
	6,  // 23: t4doc.v1.DocumentStore.Get:output_type -> t4doc.v1.GetDocumentResponse
	4,  // 24: t4doc.v1.DocumentStore.Delete:output_type -> t4doc.v1.WriteDocumentResponse
	4,  // 25: t4doc.v1.DocumentStore.Patch:output_type -> t4doc.v1.WriteDocumentResponse
	10, // 26: t4doc.v1.DocumentStore.Find:output_type -> t4doc.v1.FindResponse
	2,  // 27: t4doc.v1.DocumentStore.FindStream:output_type -> t4doc.v1.Document
	12, // 28: t4doc.v1.DocumentStore.Watch:output_type -> t4doc.v1.Change
	14, // 29: t4doc.v1.DocumentStore.CreateIndex:output_type -> t4doc.v1.CreateIndexResponse
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_t4doc_v1_document_proto_init() }
func file_proto_t4doc_v1_document_proto_init() {
	if File_proto_t4doc_v1_document_proto != nil {
		return
	}
	file_proto_t4doc_v1_document_proto_msgTypes[14].OneofWrappers = []any{
		(*Filter_Eq)(nil),
		(*Filter_And)(nil),
	}
	file_proto_t4doc_v1_document_proto_msgTypes[17].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_Int64Value)(nil),
		(*Value_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_t4doc_v1_document_proto_rawDesc), len(file_proto_t4doc_v1_document_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_t4doc_v1_document_proto_goTypes,
		DependencyIndexes: file_proto_t4doc_v1_document_proto_depIdxs,
		EnumInfos:         file_proto_t4doc_v1_document_proto_enumTypes,
		MessageInfos:      file_proto_t4doc_v1_document_proto_msgTypes,
	}.Build()
	File_proto_t4doc_v1_document_proto = out.File
	file_proto_t4doc_v1_document_proto_goTypes = nil
	file_proto_t4doc_v1_document_proto_depIdxs = nil
}
