// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/t4doc/v1/document.proto

package t4docpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentStore_Insert_FullMethodName      = "/t4doc.v1.DocumentStore/Insert"
	DocumentStore_Put_FullMethodName         = "/t4doc.v1.DocumentStore/Put"
	DocumentStore_Get_FullMethodName         = "/t4doc.v1.DocumentStore/Get"
	DocumentStore_Delete_FullMethodName      = "/t4doc.v1.DocumentStore/Delete"
	DocumentStore_Patch_FullMethodName       = "/t4doc.v1.DocumentStore/Patch"
	DocumentStore_Find_FullMethodName        = "/t4doc.v1.DocumentStore/Find"
	DocumentStore_FindStream_FullMethodName  = "/t4doc.v1.DocumentStore/FindStream"
	DocumentStore_Watch_FullMethodName       = "/t4doc.v1.DocumentStore/Watch"
	DocumentStore_CreateIndex_FullMethodName = "/t4doc.v1.DocumentStore/CreateIndex"
)

// DocumentStoreClient is the client API for DocumentStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentStoreClient interface {
	Insert(ctx context.Context, in *WriteDocumentRequest, opts ...grpc.CallOption) (*WriteDocumentResponse, error)
	Put(ctx context.Context, in *WriteDocumentRequest, opts ...grpc.CallOption) (*WriteDocumentResponse, error)
	Get(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	Delete(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*WriteDocumentResponse, error)
	Patch(ctx context.Context, in *PatchDocumentRequest, opts ...grpc.CallOption) (*WriteDocumentResponse, error)
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	FindStream(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Document], error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Change], error)
	CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error)
}

type documentStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentStoreClient(cc grpc.ClientConnInterface) DocumentStoreClient {
	return &documentStoreClient{cc}
}

func (c *documentStoreClient) Insert(ctx context.Context, in *WriteDocumentRequest, opts ...grpc.CallOption) (*WriteDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentStore_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Put(ctx context.Context, in *WriteDocumentRequest, opts ...grpc.CallOption) (*WriteDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentStore_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Get(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentStore_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Delete(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*WriteDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentStore_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Patch(ctx context.Context, in *PatchDocumentRequest, opts ...grpc.CallOption) (*WriteDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentStore_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, DocumentStore_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) FindStream(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Document], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocumentStore_ServiceDesc.Streams[0], DocumentStore_FindStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FindRequest, Document]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_FindStreamClient = grpc.ServerStreamingClient[Document]

func (c *documentStoreClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Change], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocumentStore_ServiceDesc.Streams[1], DocumentStore_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, Change]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_WatchClient = grpc.ServerStreamingClient[Change]

func (c *documentStoreClient) CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIndexResponse)
	err := c.cc.Invoke(ctx, DocumentStore_CreateIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentStoreServer is the server API for DocumentStore service.
// All implementations must embed UnimplementedDocumentStoreServer
// for forward compatibility.
type DocumentStoreServer interface {
	Insert(context.Context, *WriteDocumentRequest) (*WriteDocumentResponse, error)
	Put(context.Context, *WriteDocumentRequest) (*WriteDocumentResponse, error)
	Get(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	Delete(context.Context, *DeleteDocumentRequest) (*WriteDocumentResponse, error)
	Patch(context.Context, *PatchDocumentRequest) (*WriteDocumentResponse, error)
	Find(context.Context, *FindRequest) (*FindResponse, error)
	FindStream(*FindRequest, grpc.ServerStreamingServer[Document]) error
	Watch(*WatchRequest, grpc.ServerStreamingServer[Change]) error
	CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error)
	mustEmbedUnimplementedDocumentStoreServer()
}

// UnimplementedDocumentStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentStoreServer struct{}

func (UnimplementedDocumentStoreServer) Insert(context.Context, *WriteDocumentRequest) (*WriteDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedDocumentStoreServer) Put(context.Context, *WriteDocumentRequest) (*WriteDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedDocumentStoreServer) Get(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDocumentStoreServer) Delete(context.Context, *DeleteDocumentRequest) (*WriteDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDocumentStoreServer) Patch(context.Context, *PatchDocumentRequest) (*WriteDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedDocumentStoreServer) Find(context.Context, *FindRequest) (*FindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedDocumentStoreServer) FindStream(*FindRequest, grpc.ServerStreamingServer[Document]) error {
	return status.Errorf(codes.Unimplemented, "method FindStream not implemented")
}
func (UnimplementedDocumentStoreServer) Watch(*WatchRequest, grpc.ServerStreamingServer[Change]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedDocumentStoreServer) CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIndex not implemented")
}
func (UnimplementedDocumentStoreServer) mustEmbedUnimplementedDocumentStoreServer() {}
func (UnimplementedDocumentStoreServer) testEmbeddedByValue()                       {}

// UnsafeDocumentStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentStoreServer will
// result in compilation errors.
type UnsafeDocumentStoreServer interface {
	mustEmbedUnimplementedDocumentStoreServer()
}

func RegisterDocumentStoreServer(s grpc.ServiceRegistrar, srv DocumentStoreServer) {
	// If the following call pancis, it indicates UnimplementedDocumentStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentStore_ServiceDesc, srv)
}

func _DocumentStore_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Insert(ctx, req.(*WriteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Put(ctx, req.(*WriteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Get(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Delete(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Patch(ctx, req.(*PatchDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_FindStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FindRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocumentStoreServer).FindStream(m, &grpc.GenericServerStream[FindRequest, Document]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_FindStreamServer = grpc.ServerStreamingServer[Document]

func _DocumentStore_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocumentStoreServer).Watch(m, &grpc.GenericServerStream[WatchRequest, Change]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_WatchServer = grpc.ServerStreamingServer[Change]

func _DocumentStore_CreateIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).CreateIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_CreateIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).CreateIndex(ctx, req.(*CreateIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentStore_ServiceDesc is the grpc.ServiceDesc for DocumentStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "t4doc.v1.DocumentStore",
	HandlerType: (*DocumentStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _DocumentStore_Insert_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _DocumentStore_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DocumentStore_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DocumentStore_Delete_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _DocumentStore_Patch_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _DocumentStore_Find_Handler,
		},
		{
			MethodName: "CreateIndex",
			Handler:    _DocumentStore_CreateIndex_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FindStream",
			Handler:       _DocumentStore_FindStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _DocumentStore_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/t4doc/v1/document.proto",
}
